name: Deploy to Kubernetes via pendeploy-simple API

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Untuk memicu workflow secara manual dari UI GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger Deployment API
        env:
          DEPLOYMENT_CONFIG: ${{ secrets.DEPLOYMENT_CONFIG }}
          PENDEPLOY_API_KEY: ${{ secrets.API_KEY }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL}}
        run: |
          # Create dynamic image tag
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          DYNAMIC_IMAGE_TAG="localhost:5000/${REPO_NAME}:${{ github.sha }}"
          
          echo "🏷️ Dynamic image tag: $DYNAMIC_IMAGE_TAG"
          
          # Check if API key is set
          if [ -z "$PENDEPLOY_API_KEY" ]; then
            echo "❌ ERROR: PENDEPLOY_API_KEY is not set in GitHub secrets"
            exit 1
          fi
          
          # Validate JSON format first
          echo "$DEPLOYMENT_CONFIG" | jq . > /dev/null || (echo "❌ Invalid JSON format!" && exit 1)
          
          # Inject dynamic registry and environment variables to JSON config
          UPDATED_CONFIG=$(echo "$DEPLOYMENT_CONFIG" | jq --arg image "$DYNAMIC_IMAGE_TAG" --arg github_url "https://github.com/${{ github.repository }}" --arg api_url "https://api.millabindonesia.com" '
            .githubUrl = $github_url |
            .env.IMAGE_REGISTRY = $image |
            .env.NEXT_PUBLIC_API_URL = $api_url
          ')
          
          echo "✅ Successfully updated deployment config"
          echo "📡 Sending deployment request..."
          
          # Send the updated config with API key authentication
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "X-API-Key: $PENDEPLOY_API_KEY" \
            -d "$UPDATED_CONFIG" \
            https://api.millab-kubernetes.isacitra.com/create-deployment
        
      - name: Deployment Details
        run: |
          echo "Deployment request sent to pendeploy-simple API"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Image: localhost:5000/millab-frontend:${{ github.sha }}"