name: Deploy to Kubernetes via pendeploy-simple API

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Untuk memicu workflow secara manual dari UI GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger Deployment API
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{
              "githubUrl": "https://github.com/${{ github.repository }}",
              "env": {
                "IMAGE_REGISTRY": "localhost:5000/millab-frontend:${{ github.sha }}",
                "NEXT_PUBLIC_API_URL": "https://millab-backend.up.railway.app",
                "NODE_ENV": "production",
                "NEXT_TELEMETRY_DISABLED": "1",
                "NEXT_FORCE_DOWNLOAD_BINARY": "1"
              }
            }' \
            https://api.millab-kubernetes.isacitra.com/create-deployment
        
      - name: Deployment Details
        run: |
          echo "Deployment request sent to pendeploy-simple API"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Image: localhost:5000/millab-frontend:${{ github.sha }}"